apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuhog
  namespace: trading-2
  labels:
    app: trading
    service: cpuhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: cpuhog
  template:
    metadata:
      labels:
        app: trading
        service: cpuhog
    spec:
      tolerations:
      - key: "REGION"
        operator: "Equal"
        value: "2"
        effect: "PreferNoSchedule"
      containers:
        - name: cpuhog
          image: $REPO/cpuhog:$COURSE
          imagePullPolicy: Always
      restartPolicy: Always