version: "3"
virtualmachines:
- name: es3-api
  image: elastic-pmm/es3-api-v2
  shell: /bin/bash
  environment:
    PRODUCT_TIER: complete
    PROJECT_TYPE: observability
    REGIONS: aws-us-east-1
  memory: 4096
  cpus: 1
- name: k3s
  image: elastic-pmm/instruqt-k3s-v1
  shell: /bin/bash
  environment:
    PROXY_ES_KEY_BROKER: http://es3-api:8081
  memory: 16384
  cpus: 4
secrets:
- name: ESS_CLOUD_API_KEY
