apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-role
  namespace: $NAMESPACE
rules:
- apiGroups: ["apps"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-account
  namespace: $NAMESPACE
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-binding
  namespace: $NAMESPACE
subjects:
- kind: ServiceAccount
  name: chaos-account
  namespace: $NAMESPACE
roleRef:
  kind: Role
  name: chaos-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos
  namespace: $NAMESPACE
  labels:
    app: trading
    service: chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: chaos
  template:
    metadata:
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
      labels:
        app: trading
        service: chaos
        app.kubernetes.io/version: "$SERVICE_VERSION"
    spec:
      serviceAccountName: chaos-account
      tolerations:
      - key: "REGION"
        operator: "Equal"
        value: "$REGION"
        effect: "PreferNoSchedule"
      containers:
        - name: chaos
          image: $REPO/chaos:$COURSE
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: "$NAMESPACE"
            - name: REPO
              value: "$REPO"
            - name: COURSE
              value: "$COURSE"
            - name: REGION
              value: "$REGION"

            - name: POSTGRESQL_HOST
              value: $POSTGRESQL_HOST
            - name: POSTGRESQL_PASSWORD
              value: $POSTGRESQL_PASSWORD
            - name: POSTGRESQL_USER
              value: $POSTGRESQL_USER
            - name: POSTGRESQL_DBNAME
              value: $POSTGRESQL_DBNAME
            - name: DB_PROTOCOL
              value: $DB_PROTOCOL
            - name: DB_SETUP
              value: $DB_SETUP
            - name: DB_OPTIONS
              value: $DB_OPTIONS
            - name: DB_PORT
              value: "$DB_PORT"
            - name: DB_DIALECT
              value: $DB_DIALECT

            - name: SERVICE_VERSION
              value: "$SERVICE_VERSION"
            - name: NOTIFIER_ENDPOINT
              value: "$NOTIFIER_ENDPOINT"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: chaos
  name: chaos-ext
  namespace: $NAMESPACE
spec:
  ports:
    - name: chaos
      port: 8081
      targetPort: 10000
  type: LoadBalancer
  selector:
    app: trading
    service: chaos
---