---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading
    service: recorder-go
  name: recorder-go
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: recorder-go
  template:
    metadata:
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
        instrumentation.opentelemetry.io/inject-sdk: "opentelemetry-operator-system/elastic-instrumentation"
        resource.opentelemetry.io/service.version: "$SERVICE_VERSION"
      labels:
        app: trading
        service: recorder-go
        app.kubernetes.io/version: "$SERVICE_VERSION"
    spec:
      containers:
        - env:
            - name: MSSQL_HOST
              value: $MSSQL_HOST
            - name: MSSQL_PASSWORD
              value: $MSSQL_PASSWORD
            - name: MSSQL_USER
              value: $MSSQL_USER
            - name: MSSQL_DBNAME
              value: $MSSQL_DBNAME
            - name: MSSQL_PROTOCOL
              value: $MSSQL_PROTOCOL
            - name: MSSQL_SETUP
              value: $MSSQL_SETUP
            - name: MSSQL_OPTIONS
              value: $MSSQL_OPTIONS
            - name: MSSQL_PORT
              value: "$MSSQL_PORT"
            - name: MSSQL_DIALECT
              value: $MSSQL_DIALECT
          image: $REPO/recorder-go:$COURSE
          imagePullPolicy: Always
          name: recorder-go
          ports:
            - containerPort: 9003
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: recorder-go
  name: recorder-go
  namespace: $NAMESPACE
spec:
  ports:
    - name: recorder-go
      port: 9003
      targetPort: 9003
  selector:
    app: trading
    service: recorder-go
---