---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading
    service: recorder-go
  name: recorder-go
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: recorder-go
  template:
    metadata:
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
        instrumentation.opentelemetry.io/inject-sdk: "opentelemetry-operator-system/elastic-instrumentation"
        resource.opentelemetry.io/service.version: "$SERVICE_VERSION"
      labels:
        app: trading
        service: recorder-go
        app.kubernetes.io/version: "$SERVICE_VERSION"
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: $MYSQL_HOST
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD
            - name: MYSQL_USER
              value: $MYSQL_USER
            - name: MYSQL_PORT
              value: "$MYSQL_PORT"
          image: $REPO/recorder-go:$COURSE
          imagePullPolicy: Always
          name: recorder-go
          ports:
            - containerPort: 9003
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: recorder-go
  name: recorder-go
  namespace: $NAMESPACE
spec:
  ports:
    - name: recorder-go
      port: 9003
      targetPort: 9003
  selector:
    app: trading
    service: recorder-go
---