---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading
    service: recorder-go-zero
  name: recorder-go-zero
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: recorder-go-zero
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "opentelemetry-operator-system/elastic-instrumentation"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/recorder-zero"
        io.opentelemetry.discovery.logs/enabled: "true"
      labels:
        app: trading
        service: recorder-go-zero
    spec:
      tolerations:
      - key: "REGION"
        operator: "Equal"
        value: "$REGION"
        effect: "PreferNoSchedule"
      containers:
        - env:
            - name: POSTGRESQL_HOST
              value: $POSTGRESQL_HOST
            - name: POSTGRESQL_PASSWORD
              value: $POSTGRESQL_PASSWORD
            - name: POSTGRESQL_USER
              value: $POSTGRESQL_USER
            - name: POSTGRESQL_SSLMODE
              value: "$POSTGRESQL_SSLMODE"
          image: $REPO/recorder-go-zero:$COURSE
          imagePullPolicy: Always
          name: recorder-go-zero
          ports:
            - containerPort: 9003
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: recorder-go-zero
  name: recorder-go-zero
  namespace: $NAMESPACE
spec:
  ports:
    - name: recorder-go-zero
      port: 9003
      targetPort: 9003
  selector:
    app: trading
    service: recorder-go-zero
---